dist: trusty
language: ruby
rvm:
 - 2.0.0
 - 2.2.8
 - 2.3.5
 - 2.4.0
 - ruby-head
 - jruby-9.1.14.0
 - rbx-2
matrix:
 allow_failures:
  - rvm: ruby-head
  - rvm: rbx-2
before_install:
 - gem install bundler
 - bundle --version
 - gem --version
script:
 - bundle exec rake test_cov
